#logging:
#config: classpath:logback-spring.xml  #指定配置文件
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
  servlet:
    session:
      cookie:
        http-only: true #如果为true，那么浏览器脚本将无法访问cookie
        secure: false #如果为true，那么cookie将仅通过HTTPS连接发送

spring:
  redis:
    open: true       # 是否开启redis缓存  true开启   false关闭
    #host: 139.196.44.166  # Redis服务器地址
    host: 127.0.0.1  # Redis服务器地址
    database: 0      # Redis数据库索引（默认为0）
    port: 6379       # Redis服务器连接端口
    password: 123456 # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5
  jackson:
    time-zone: GMT+8
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      maxFileSize: 100MB
      maxRequestSize: 100MB
  profiles:
    active: demo
  mvc:
    async:
      request-timeout: 20000
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
#------------------------------------------#
#                                          #
#            mybatis plus 配置              #
#                                          #
#------------------------------------------#
#mybatis plus
mybatis-plus:
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: org.lvb.shopsmall.lib.**.entity
  global-config:
    #刷新mapper 调试神器
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: ID_WORKER
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: not_empty
      #数据库大写下划线转换
      capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: MYSQL
    banner: false
  configuration:
    #驼峰下划线转换#驼峰下划线转换
    map-underscore-to-camel-case: false
    cache-enabled: true #开启二级缓存
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    lazy-loading-enabled: true #设置为true为打开延迟加载 实体类必须加上这个注解@JsonIgnoreProperties(value = {"handler"}) 否则将会报com.fasterxml.jackson.databind.exc.InvalidDefinitionException错误
    aggressive-lazy-loading: false #将积极加载改为消极加载，即延迟加载
fdfs:
  connect-timeout: 691
  so-timeout: 1501
  tracker-list: 121.43.187.3:22122
  pool:
    jmx-enabled: false

wechat:
  appid: wx47b3a34572fa0c6c
  secret: c820766ffb4c34032f2ccb1cf84e4cd5




