spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.14.180.98:3306/dxs_youxiu?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: nbuser
    password: 8]rD2yjPGrW-*7(N
    ##  jdbc:mysql://192.168.0.161:8520/newbusiness?useUtf8=true;autoReconnect=true;failOverReadOnly=false
    ## yiqian901  ZcR7iVGrdxs
### update file path
config:
  localhost:  https://wechat.cnyto.me/
  fileServer: https://static.cnyto.me/
  uploadServer: http://172.19.142.166:8080/Upload
  extraUserOrderdetail: msg.user.orderdetail
  extraUserCkeckorder: msg.user.ckeckorder
  extraShopOrderdetail: msg.shop.orderdetail
  extraExpressPacketdetail: msg.express.packetdetail
  extraSystem: msg.system







